#!/usr/bin/env python3
"""
Make the subtitle the randomizer draws under the "Pokemon Stadium" logo on the title
screen, and write it as an RGBA32 texture for the game (src/fragments/36/randomizer_title.c):

    tools/randomizer/gen_title_subtitle.py --text "RANDOMIZER" OUT.h [--preview PNG]
    tools/randomizer/gen_title_subtitle.py --png ARTWORK.png OUT.h [--preview PNG]

--text draws the text in the placeholder style: bold italic, yellow with a blue outline
and a dark shadow, like the logo's "POKeMON". --png takes finished artwork instead (any
size, with transparency), scaled to the subtitle's height. The title screen is 320x240,
so the subtitle is drawn at that size: 24 pixels high and up to 300 wide.

Needs ImageMagick (`convert`). The header is generated: don't edit it by hand.
"""

import argparse
import os
import subprocess
import sys
import tempfile

HEIGHT = 24
MAX_WIDTH = 300
FONT = "/usr/share/fonts/truetype/freefont/FreeSansBoldOblique.ttf"
FILL = "#FFD200"
OUTLINE = "#1A3C8E"
SHADOW = "#0A0F24"


def run(*args):
    subprocess.run(["convert", *args], check=True)


def render_text(text, out, tmp):
    """The placeholder style, drawn at 4x and scaled down so the edges are smooth."""
    fill = os.path.join(tmp, "fill.png")
    outline = os.path.join(tmp, "outline.png")
    shadow = os.path.join(tmp, "shadow.png")
    run("-background", "none", "-font", FONT, "-pointsize", "100", "-fill", FILL, "label:" + text,
        "-bordercolor", "none", "-border", "24", fill)
    run(fill, "-alpha", "extract", "-morphology", "Dilate", "Disk:9", "-background", OUTLINE, "-alpha", "shape",
        outline)
    run(fill, "-alpha", "extract", "-morphology", "Dilate", "Disk:13", "-background", SHADOW, "-alpha", "shape",
        "-page", "+0+6", "-background", "none", "-flatten", shadow)
    run(shadow, outline, "-compose", "over", "-composite", fill, "-compose", "over", "-composite", "-trim",
        "+repage", "-filter", "Lanczos", "-resize", f"x{HEIGHT}", out)


def scale_artwork(src, out):
    run(src, "-trim", "+repage", "-filter", "Lanczos", "-resize", f"x{HEIGHT}", out)


def read_rgba(path):
    """The image's size and pixels, with its rows padded to a power of two: the game
    loads the texture a few rows at a time (gDPLoadTextureBlock), and rows of any other
    length come out with their last pixels scrambled on every other row."""
    size = subprocess.run(["identify", "-format", "%w %h", path], check=True, capture_output=True, text=True)
    width, height = map(int, size.stdout.split())
    padded = 4
    while padded < width:
        padded *= 2
    raw = subprocess.run(
        ["convert", path, "-background", "none", "-gravity", "west", "-extent", f"{padded}x{height}", "rgba:-"],
        check=True,
        capture_output=True,
    ).stdout
    return width, padded, height, raw


def write_header(path, width, padded, height, raw, source):
    words = [int.from_bytes(raw[i : i + 8], "big") for i in range(0, len(raw), 8)]
    with open(path, "w") as f:
        f.write("// Generated by tools/randomizer/gen_title_subtitle.py. Do not edit.\n")
        f.write(f"// {source}\n")
        f.write("// The title screen's subtitle: RGBA32, two pixels to a u64 so it's 8-byte aligned,\n")
        f.write("// RANDOMIZER_SUBTITLE_W wide, in rows RANDOMIZER_SUBTITLE_TEX_W long.\n")
        f.write("// Included once, by randomizer_title.c.\n\n")
        f.write(f"#define RANDOMIZER_SUBTITLE_W {width}\n")
        f.write(f"#define RANDOMIZER_SUBTITLE_TEX_W {padded}\n")
        f.write(f"#define RANDOMIZER_SUBTITLE_H {height}\n\n")
        f.write("static u64 sRandomizerSubtitle[] = {\n")
        for i in range(0, len(words), 4):
            f.write("    " + ", ".join(f"0x{w:016X}" for w in words[i : i + 4]) + ",\n")
        f.write("};\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--text", help="the subtitle, drawn in the placeholder style")
    group.add_argument("--png", help="finished artwork to use instead")
    parser.add_argument("out", help="the header to write")
    parser.add_argument("--preview", help="also write the subtitle as a PNG")
    args = parser.parse_args()

    with tempfile.TemporaryDirectory() as tmp:
        image = os.path.join(tmp, "subtitle.png")
        if args.text:
            render_text(args.text, image, tmp)
            source = f'--text "{args.text}"'
        else:
            scale_artwork(args.png, image)
            source = f"--png {os.path.basename(args.png)}"
        width, padded, height, raw = read_rgba(image)
        if width > MAX_WIDTH:
            sys.exit(f"The subtitle is {width} pixels wide at {HEIGHT} high; the most is {MAX_WIDTH}")
        write_header(args.out, width, padded, height, raw, source)
        if args.preview:
            run(image, args.preview)
    print(f"{args.out}: {width}x{height}")


if __name__ == "__main__":
    main()
