#!/usr/bin/env python3
"""
Draw the Z button icon the randomizer's control hints use, in the style of the
game's own L and R button icons (grey rounded button, white letter with a dark
outline), and write it as a 32x24 RGBA16 texture for the game to draw:

    tools/randomizer/gen_z_icon.py src/fragments/randomizer_z_icon.h [--png PREVIEW]

The icon is drawn from scratch here, not copied from the game.
"""

import argparse
import struct
import zlib

WIDTH = 32
HEIGHT = 24
BUTTON_W = 26  # like the L and R icons, the rest of the texture is transparent
RADIUS = 8

# The Z, on a 10x12 grid: # is the letter, the outline is added around it
GLYPH = [
    "##########",
    "##########",
    "#######...",
    "......###.",
    ".....###..",
    "....###...",
    "...###....",
    "..###.....",
    ".###......",
    "###.......",
    "##########",
    "##########",
]
GLYPH_X = (BUTTON_W - len(GLYPH[0])) // 2
GLYPH_Y = (HEIGHT - len(GLYPH)) // 2


def inside_button(x, y, inset=0):
    """Whether (x, y) is inside the rounded button shrunk by inset pixels."""
    left, right = inset, BUTTON_W - 1 - inset
    top, bottom = inset, HEIGHT - 1 - inset
    r = RADIUS - inset
    if not (left <= x <= right and top <= y <= bottom):
        return False
    cx = min(max(x, left + r), right - r)
    cy = min(max(y, top + r), bottom - r)
    return (x - cx) ** 2 + (y - cy) ** 2 <= r * r + r


def glyph_at(x, y):
    gx, gy = x - GLYPH_X, y - GLYPH_Y
    return 0 <= gy < len(GLYPH) and 0 <= gx < len(GLYPH[0]) and GLYPH[gy][gx] == "#"


def near_glyph(x, y):
    return any(glyph_at(x + dx, y + dy) for dx in (-1, 0, 1) for dy in (-1, 0, 1))


def shade(x, y):
    """5-bit grey level of the pixel, or None where it's transparent."""
    if not inside_button(x, y):
        return None
    if not inside_button(x, y, 1):
        return 8  # dark rim
    if glyph_at(x, y):
        return 31
    if near_glyph(x, y):
        return 5
    if not inside_button(x, y, 2):
        # lit from above: bright top edge, shadowed bottom edge
        return 26 if y < HEIGHT // 2 else 11
    # body: light at the top, darker towards the bottom
    return round(28 - (y - 2) * 10 / (HEIGHT - 5))


def rgba16(level):
    if level is None:
        return 0
    return (level << 11) | (level << 6) | (level << 1) | 1


def pixels():
    return [rgba16(shade(x, y)) for y in range(HEIGHT) for x in range(WIDTH)]


def write_header(path, px):
    words = []
    for i in range(0, len(px), 4):
        a, b, c, d = px[i : i + 4]
        words.append((a << 48) | (b << 32) | (c << 16) | d)
    lines = [
        "// Generated by tools/randomizer/gen_z_icon.py. Do not edit.",
        "// The Z button icon for the randomizer's control hints, drawn in the style of the",
        "// game's L and R button icons: 32x24 RGBA16. Included once by each fragment that",
        "// draws it.",
        "",
        f"#define RANDOMIZER_Z_ICON_W {WIDTH}",
        f"#define RANDOMIZER_Z_ICON_H {HEIGHT}",
        "",
        "static u64 sRandomizerZIcon[] = {",
    ]
    for i in range(0, len(words), 4):
        lines.append("    " + " ".join(f"0x{w:016X}," for w in words[i : i + 4]))
    lines.append("};")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


def write_png(path, px, scale=4):
    rows = []
    for y in range(HEIGHT * scale):
        row = bytearray([0])
        for x in range(WIDTH * scale):
            v = px[(y // scale) * WIDTH + x // scale]
            r, g, b = (((v >> s) & 31) * 255 // 31 for s in (11, 6, 1))
            row += bytes((r, g, b, 255 if v & 1 else 0))
        rows.append(bytes(row))

    def chunk(kind, data):
        return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF)

    header = struct.pack(">IIBBBBB", WIDTH * scale, HEIGHT * scale, 8, 6, 0, 0, 0)
    with open(path, "wb") as f:
        f.write(b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", header) + chunk(b"IDAT", zlib.compress(b"".join(rows))))
        f.write(chunk(b"IEND", b""))


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("header")
    parser.add_argument("--png", help="also write a 4x preview")
    args = parser.parse_args()

    px = pixels()
    write_header(args.header, px)
    if args.png:
        write_png(args.png, px)


if __name__ == "__main__":
    main()
