/*
 * The title screen's subtitle, under the "Pokemon Stadium" logo (randomizer_title, see
 * randomizer_title.h), over the 3D scene (randomizer_title_arena.c) with the logo
 * (randomizer_title_logo.c). The logo and the subtitle fade in as the screen starts. The
 * picture is generated by tools/randomizer/gen_title_subtitle.py, from text in a
 * placeholder style or from finished artwork. Built only with RANDOMIZER=1; empty otherwise
 * so the default build still matches.
 */
#include "randomizer_title.h"

#ifdef RANDOMIZER

#include "src/1CF30.h"
#include "src/20470.h"
#include "randomizer_title_subtitle.h"

#define SCREEN_W 320
#define SUBTITLE_Y 62 // just under the logo (58 high from line 3): the two take the top third
#define FADE_FRAMES 16

// The texture memory holds 1024 RGBA32 pixels, so the subtitle goes in strips of rows
#define STRIP_ROWS (1024 / RANDOMIZER_SUBTITLE_TEX_W)

static void Randomizer_TitleDraw(s32 arg0, s32 arg1);

static RandomizerTitleHooks sHooks = {
    Randomizer_TitleDraw,
};

static s32 sFrames;

// The subtitle in rows a power of two long, which texture loads need (gDPLoadTextureBlock
// scrambles the last pixels of every other row otherwise); the ROM only has its pixels,
// compressed
static u64 sTexture[(RANDOMIZER_SUBTITLE_TEX_W * RANDOMIZER_SUBTITLE_H) / 2];

RandomizerTitleHooks* Randomizer_TitleEntry(void) {
    u8* texture = (u8*)sTexture;
    s32 row;

    // Fragments aren't cleared when they're loaded
    sFrames = 0;

    // The pixels, row after row, then each row moved out to its place from the last one
    // back, so none is overwritten before it's moved (bcopy copes with the overlap)
    Yay0_Decompress(sRandomizerSubtitleYay0, texture);
    for (row = RANDOMIZER_SUBTITLE_H - 1; row >= 0; row--) {
        bcopy(texture + row * RANDOMIZER_SUBTITLE_W * 4, texture + row * RANDOMIZER_SUBTITLE_TEX_W * 4,
              RANDOMIZER_SUBTITLE_W * 4);
        bzero(texture + (row * RANDOMIZER_SUBTITLE_TEX_W + RANDOMIZER_SUBTITLE_W) * 4,
              (RANDOMIZER_SUBTITLE_TEX_W - RANDOMIZER_SUBTITLE_W) * 4);
    }
    Randomizer_LogoLoad();
    Randomizer_ArenaStart();
    return &sHooks;
}

// Every frame, after the background and "PRESS START"; the game's own arguments (a
// position) aren't used
static void Randomizer_TitleDraw(UNUSED s32 arg0, UNUSED s32 arg1) {
    s32 x = (SCREEN_W - RANDOMIZER_SUBTITLE_W) / 2;
    s32 row;

    if (sFrames < FADE_FRAMES) {
        sFrames++;
    }

    Randomizer_ArenaDraw();
    Randomizer_LogoDraw((sFrames * 255) / FADE_FRAMES);

    gSPDisplayList(gDisplayListHead++, D_8006F518);
    gDPSetEnvColor(gDisplayListHead++, 255, 255, 255, (sFrames * 255) / FADE_FRAMES);
    for (row = 0; row < RANDOMIZER_SUBTITLE_H; row += STRIP_ROWS) {
        s32 rows = ((RANDOMIZER_SUBTITLE_H - row) < STRIP_ROWS) ? (RANDOMIZER_SUBTITLE_H - row) : STRIP_ROWS;

        func_8001C8C4(x, SUBTITLE_Y + row, RANDOMIZER_SUBTITLE_W, rows,
                      (u8*)sTexture + (row * RANDOMIZER_SUBTITLE_TEX_W * 4), RANDOMIZER_SUBTITLE_TEX_W, 0);
    }
    gSPDisplayList(gDisplayListHead++, D_8006F630);
}

#endif
